WEBHOOK_EVENTS = [
    "incident_triggered",
    "incident_assigned",
    "incident_reassigned",
    "incident_severity_changed",
    "incident_validity_changed",
    "incident_resolved",
    "incident_ignored",
    "incident_reopened",
    "incident_regression",
    "incident_access_granted",
    "incident_access_revoked",
    "incident_shared_publicly",
    "incident_unshared_publicly",
    "issue_feedback_received",
    "new_occurrence",
    "incident_note_created",
]
