resources:
  - kind: source
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id|tostring
          title: '(.type + " - " + .full_name)'
          blueprint: '"gitguardianSource"'
          properties:
            id: .my_enum
            sourceType: .type
            fullName: .full_name
            url: .url
            health: .health
            sourceCriticality: .source_criticality
            openIncidentsCount: .open_incidents_count
            openIncidentsSeverityBreakdown.critical: .secret_incidents_breakdown.open_secret_incidents.severity_breakdown.critical
            openIncidentsSeverityBreakdown.high: .secret_incidents_breakdown.open_secret_incidents.severity_breakdown.high
            openIncidentsSeverityBreakdown.medium: .secret_incidents_breakdown.open_secret_incidents.severity_breakdown.medium
            openIncidentsSeverityBreakdown.low: .secret_incidents_breakdown.open_secret_incidents.severity_breakdown.low
            openIncidentsSeverityBreakdown.info: .secret_incidents_breakdown.open_secret_incidents.severity_breakdown.info
            openIncidentsSeverityBreakdown.unknown: .secret_incidents_breakdown.open_secret_incidents.severity_breakdown.unknown
            closedIncidentsCount: .closed_incidents_count
            closedIncidentsSeverityBreakdown.critical: .secret_incidents_breakdown.closed_secret_incidents.severity_breakdown.critical
            closedIncidentsSeverityBreakdown.high: .secret_incidents_breakdown.closed_secret_incidents.severity_breakdown.high
            closedIncidentsSeverityBreakdown.medium: .secret_incidents_breakdown.closed_secret_incidents.severity_breakdown.medium
            closedIncidentsSeverityBreakdown.low: .secret_incidents_breakdown.closed_secret_incidents.severity_breakdown.low
            closedIncidentsSeverityBreakdown.info: .secret_incidents_breakdown.closed_secret_incidents.severity_breakdown.info
            closedIncidentsSeverityBreakdown.unknown: .secret_incidents_breakdown.closed_secret_incidents.severity_breakdown.unknown
            lastScan.date: .last_scan.date
            lastScan.status: .last_scan.status
            lastScan.failingReason: .last_scan.failing_reason
            lastScan.commitScanned: .last_scan.commits_scanned
            lastScan.duration: .last_scan.duration
            lastScan.branchesScanned: .last_scan.branches_scanned
            lastScan.progress: .last_scan.progress
            visibility: .visibility
  - kind: secret_detector
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .name
          title: .display_name
          blueprint: '"gitguardianSecretDetector"'
          properties:
            name: .name
            displayName: .display_name
            type: .type
            category: .category
            isActive: .is_active
            scansCodeOnly: .scans_code_only
            checkable: .checkable
            useWithValidityCheckDisabled: .use_with_validity_check_disabled
            frequency: .frequency
            removedAt: .removed_at
            openIncidentsCount: .open_incidents_count
            ignoredIncidentsCount: .ignored_incidents_count
            resolvedIncidentsCount: .resolved_incidents_count
  - kind: internal_secret_incident
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id|tostring
          title: (.id | tostring) + "-" + .detector.name
          blueprint: '"gitguardianInternalIncident"'
          properties:
            id: .id
            date: .date
            detector.name: .detector.name
            detector.displayName: .detector.display_name
            detector.nature: .detector.nature
            detector.family: .detector.family
            detector.detectorGroupName: .detector.detector_group_name
            detector.detectorGroupDisplayName: .detector.detector_group_display_name
            secretId: .secret_id
            gitguardianUrl: .gitguardian_url
            regression: .regression
            status: .status
            occurrencesCount: .occurrences_count
            ignoreReason: .ignore_reason
            ignoredAt: .ignored_at
            secretRevoked: .secret_revoked
            severity: .severity
            validity: .validity
            resolvedAt: .resolved_at
            shareUrl: .share_url
  - kind: public_secret_incident
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id|tostring
          title: (.id | tostring) + "-" + .detector.name
          blueprint: '"gitguardianPublicIncident"'
          properties:
            id: .id
            date: .date
            detector.name: .detector.name
            detector.displayName: .detector.display_name
            detector.nature: .detector.nature
            detector.family: .detector.family
            detector.detectorGroupName: .detector.detector_group_name
            detector.detectorGroupDisplayName: .detector.detector_group_display_name
            secretId: .secret_id
            gitguardianUrl: .gitguardian_url
            regression: .regression
            status: .status
            occurrencesCount: .occurrences_count
            ignoreReason: .ignore_reason
            ignoredAt: .ignored_at
            secretRevoked: .secret_revoked
            severity: .severity
            validity: .validity
            resolvedAt: .resolved_at
            shareUrl: .share_url
            declarative_secret_status: .declarative_secret_status
  - kind: user
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id|tostring
          title: .name
          blueprint: '"gitguardianUser"'
          properties:
            id: .id
            name: .name
            email: .email
            accessLevel: .access_level
            active: .active
            createdAt: .created_at
            lastLogin: .last_login